os: osx
language: generic
sudo: false

install:
  - mkdir rgl
  - mkdir -p ~/.local/
  - echo '--no-alpn' > ~/.curlrc
  - export HOMEBREW_CURLRC=1
  - brew update
  - brew install ghc
  - curl http://www.grammaticalframework.org/download/gf-3.9-bin-intel-mac.tar.gz > gf.tar.gz
  - tar -C ~/.local/ -zxf gf.tar.gz

script:
  - sh Make.sh --gf=~/.local/bin/gf --dest=./rgl
  - runghc Make.hs build --gf=~/.local/bin/gf --dest=./rgl
