sudo: required
language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - ghc

before_install:
  - mkdir rgl
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ghc@8.2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl http://www.grammaticalframework.org/download/gf-3.9-bin-intel-mac.tar.gz > gf.tar.gz && sudo tar --no-same-owner --no-same-permissions -C /usr/local -zxf gf.tar.gz && rm gf.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl http://www.grammaticalframework.org/download/gf_3.9-1_amd64.deb > gf.deb && sudo dpkg -i gf.deb && rm gf.deb ; fi
  - ls /usr/bin
  - ls /usr/local/bin
#  - export GF_LIB_PATH=/home/rgl ;

script:
#  - runhaskell Make.hs build prelude all --verbose
  - bash Make.sh --dest=rgl --verbose
