os: osx
language: haskell

install:
  - mkdir bin
  - mkdir rgl
  - curl http://www.grammaticalframework.org/download/gf-3.9-bin-intel-mac.tar.gz > gf.tar.gz
  - tar -C bin -zxf gf.tar.gz

script:
  - sh Make.sh --gf=./bin/gf --dest=./rgl
  - runghc Make.hs build --gf=./bin/gf --dest=./rgl
